In [1]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [16]:
np.random.seed(42)

In [17]:
T = np.random.randint(low=1,high=5,size=10)
T

array([3, 4, 1, 3, 3, 4, 1, 1, 3, 2])

In [18]:
A = np.random.randint(low=1,high=10, size=10)
A

array([3, 7, 8, 5, 4, 8, 8, 3, 6, 5])

In [19]:
T/A

array([ 1.        ,  0.57142857,  0.125     ,  0.6       ,  0.75      ,
        0.5       ,  0.125     ,  0.33333333,  0.5       ,  0.4       ])

In [20]:
import sympy

In [21]:
attendants = []
for i, (t, a) in enumerate(zip(T, A)):
    t, a = int(t), int(a)
    attendants.append((sympy.Rational(t, a), 1+i))
attendants

[(1, 1),
 (4/7, 2),
 (1/8, 3),
 (3/5, 4),
 (3/4, 5),
 (1/2, 6),
 (1/8, 7),
 (1/3, 8),
 (1/2, 9),
 (2/5, 10)]

In [22]:
sorted(attendants)

[(1/8, 3),
 (1/8, 7),
 (1/3, 8),
 (2/5, 10),
 (1/2, 6),
 (1/2, 9),
 (4/7, 2),
 (3/5, 4),
 (3/4, 5),
 (1, 1)]

In [23]:
f = 0
result = []
for s, (ta, a) in enumerate(sorted(attendants), ):
    f += A[a-1]*T[a-1]
    s = s + 1
    result.append((a, f, ta, A[a-1]))
results = pd.DataFrame(data=result, columns=['a', 'f(s)', 't/alpha', 'alpha'])
results

a  f(s) t/alpha  alpha
0   3     8     1/8      8
1   7    16     1/8      8
2   8    19     1/3      3
3  10    29     2/5      5
4   6    61     1/2      8
5   9    79     1/2      6
6   2   107     4/7      7
7   4   122     3/5      5
8   5   134     3/4      4
9   1   143       1      3

In [24]:
D = np.array([5.21, 7.0, 6.41, 4.8, 5.0])
U = np.array([0.75, .61, .55, .81, .5, .45])
PU = U[[2-1, 4-1, 1-1, 5-1, 3-1]]
display(D, U, PU)

array([ 5.21,  7.  ,  6.41,  4.8 ,  5.  ])

array([ 0.75,  0.61,  0.55,  0.81,  0.5 ,  0.45])

array([ 0.61,  0.81,  0.75,  0.5 ,  0.55])

In [25]:
D.dot(PU)

18.805599999999998